MusicPlayer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("player.urls")),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

player/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = "player"

urlpatterns = [
    # path('songs/<str:name>/', views.IndexView.as_view(),name='index'),
    path("songs/<str:name>/", views.index, name='index'),
    path("", views.artists, name='artists'),
    path("signup/", views.signup, name='signup'),
    path("login/", views.loginPage, name='login'),
    path("logout/", views.logoutUser, name='logout'),
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),
    path('album/add',views.AlbumCreate.as_view(),name='album-add'),
    path("createplaylist/playlists/", views.playlists, name='playlists'),
    path("createplaylist/", views.createPlaylist, name='creat_playlist'),
    # /* path("<int:pk>/", views.PlaylistView.as_view(), name='playlists'),
    # path("createplaylist/", views.PlaylistCreate.as_view(), name='creat_playlist'),*/
]
urlpatterns += staticfiles_urlpatterns()

player/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from pickle import FALSE



class Artists(models.Model):
    name = models.TextField()
    surname = models.TextField()
    nickname = models.TextField()
    birthdate = models.DateTimeField()
    image = models.ImageField(default=None)

    def get_absolute_url(self):
        return reverse("", kwargs={"pk": self.pk})
    
    def __str__(self):
        return self.nickname

    
class Song(models.Model):
    title = models.TextField()
    artist = models.ForeignKey(Artists, on_delete=models.CASCADE)
    image = models.ImageField(default=None)
    audio_file = models.FileField(blank=True, null=True)
    audio_link = models.CharField(max_length=200, blank=True, null=True)
    duration = models.CharField(max_length=20,default='3:30')
    paginate_by = 2

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("player:detail", kwargs={"pk": self.pk})


class Playlist(models.Model):
    title = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    songs = models.ManyToManyField(Song)
    image = models.ImageField(default=None)

    def str(self):
        return self.title

player/forms.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Song, Artists,Playlist


class CreatUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username',  'password1', 'password2')


class PlaylistForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ['title', 'songs']
    title = forms.TextInput()
    user = User
    songs = forms.ModelMultipleChoiceField(
        queryset=Song.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

# class PlaylistForm(forms.ModelForm):
#     class Meta:
#         model = Playlist
#         fields = ['title', 'songs']
#     title = forms.TextField()
#     songs = forms.ModelMultipleChoiceField(
#         queryset=Song.objects.all(),
#         widget=forms.CheckboxSelectMultiple
#     )

player/views.py
# Create your views here.
from http.client import HTTPResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# imported our models
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.urls import reverse
from dataclasses import fields
from pyexpat import model
from re import template

from django.views import generic
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from .models import Song, Artists, Playlist
from .forms import CreatUserForm, PlaylistForm

def artists(request):
    context = {"page_obj": Artists.objects.all(),
               "playlists": Playlist.objects.all()}
    return render(request, "index11.html", context)

class DetailView(generic.DetailView):
    context = {"page_obj": Artists.objects.all()}
    model=Song
    template_name ='player/detail.html'
    
    
class AlbumCreate(CreateView):
    context = {"page_obj": Artists.objects.all()}
    model=Song
    fields=['title','artist','image','audio_file']

# class PlaylistCreate(CreateView):
#     context = {"page_obj": Song.objects.all()}
#     model=Playlist
#     fields = ['title','user','image','songs']

# class PlaylistView(generic.DetailView):
#     context = {"page_obj": Song.objects.all()}
#     model=Playlist
#     template_name ='player/new.html'
def createPlaylist(request):
    playlist = Playlist
    form = PlaylistForm(request.POST)
    form.user = User.objects.filter(username = request.user)[0]
    if request.method == 'POST':
        if form.is_valid():
            form.save()           
            return render(request,'playlists.html',{'playlist':playlist,'form':form})

        else:
            print(form.errors)
            
    return render(request, "createPlaylist.html", {'form': form})

# def createPlaylist(request):
#     form = PlaylistForm(request.POST)
#     form.user = User.objects.filter(username = request.user)[0]
#     if request.method == 'POST':
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect("playlists/")

#         else:
#             print(form.errors)
            
#     return render(request, "createPlaylist.html", {'form': form})
    
# @login_required(login_url='login')
def index(request, name):
    paginator = Paginator(Song.objects.filter(artist__nickname=name), 1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj}
    return render(request, "index.html", context)

# def register(request):
#     if request.method == 'POST':
#         user_form = RegistrationForm(request.POST)
#         profile_form = ProfileForm(request.POST)
#         if user_form.is_valid() and profile_form.is_valid():
#             user = user_form.save()  # ← assign the user to a variable
#             profile_form.instance.user = user  # ← set it as user of the profile
#             profile_form.save()
#             messages.success(request, f'Welcome {user.username}! Your account has been created. Sign in to continue.')
#         return redirect('login')
#     else:
#         user_form = RegistrationForm()
#         profile_form = ProfileForm()
#         return render(request, 'home/register.html', { 'user_form': user_form, 'profile_form': profile_form })
    


# @login_required(login_url='login')
def playlists(request):
    songs = Playlist.objects.all()
    paginator = Paginator(songs.songs.all(), 1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj}
    return render(request, "playlists.html", context)


def signup(request):
    form = CreatUserForm()
    if request.user.is_authenticated:
        return redirect('player:artists')
    else:
        if request.method == 'POST':
            form = CreatUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)
                return redirect(reverse('player:login'))

        context = {'form': form}
        return render(request, "signup.html", context)


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('player:artists')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('player:artists')
            else:
                messages.info(request, 'Username or password is incorrect')

        context = {}
        return render(request, "login.html", context)


# @login_required(login_url='login')
def artists(request):
    context = {"page_obj": Artists.objects.all(),
               "playlists": Playlist.objects.all()}
    return render(request, "index11.html", context)


def logoutUser(request):
    logout(request)
    return redirect('player:login')

player/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%block style%}
    <link href="{% static 'index.css' %}" rel="stylesheet"/>
    {%endblock%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Prompt:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=IM+Fell+English+SC&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital,wght@1,200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Prompt:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    
    <title>{%block title%}Main{%endblock%}</title>
</head>
<body>
    <nav class="navbar navbar-dark " style="background: rgba(0,0,0,0.25); font-family: 'IM Fell English SC', serif;">
        <div class="container-fluid">
          <img src="{% static 'Images' %}/oyo-p.png" style="width: 60px; height: 60px;" alt="">
          <div class="mx-auto">
          <a class="navbar-brand mx-0 " href="#" style="font-family: 'IM Fell English SC', serif; font-size:36px">Sanjunipero</a>       
          </div>
          
          <a class="nav-link ms-0" href="{% url 'player:logout' %} " style="color: aliceblue;">LogOut</a>
        
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'player:artists' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'player:creat_playlist' %}">Albums</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="">Songs</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'player:album-add' %}">Add Albums</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'player:signup' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'player:login' %}">Login</a>
              </li>
              
            <!-- <form class="d-flex" style="width: 450px;">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form> -->
          </div>
        </div>
      </nav>
{%block body%}   
{%endblock%}

<footer>
  <div class = "social-links">
    <a href = "#"><i class = "fab fa-facebook-f"></i></a>

    <a href = "#"><i class = "fab fa-twitter"></i></a>

    <a href = "#"><i class = "fab fa-instagram"></i></a>

    <a href = "#"><i class = "fab fa-pinterest"></i></a>
  </div>
  <span>OYU LIVE</span>
</footer>
</div>
</body>
</html>

player/templates/createPlaylist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action="">
    {% csrf_token %}
    {{ form.title }}
    {{ form.user }}
    {{ form.songs }}
    <input class="btn" type="submit" name="Create User" value="Sign In">
</form>


</body>
</html>

player/templates/form-template.html
{%for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-5">{{field.label_tag}}</label>
    <div class="col-sm-1">{{field}}</div>
</div>
{%endfor%}

player/templates/index.html
{%extends 'base.html'%}
{% load static %}
{%block title%}My Music Player{%endblock%}
{%block style%}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link href="{% static 'index.css' %}" rel="stylesheet"/>
  <link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"/>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.7/mediaelementplayer.min.css" rel="stylesheet"/>
  <link href="{% static './style.css' %}" rel="stylesheet"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.7/mediaelement-and-player.min.js">
  </script>
  <script src="{% static './script.js' %}">
  </script>
{%endblock%}

{%block body%}
    <div class="contain">
     <div class="container">
      <div class="music-player" style="height: 680px;">
        {% for item in page_obj %}
       <div class="cover">
        <img alt="" src="{{item.image.url}}" style="width: 300px;height:350px;object-fit:cover;"/>
       </div>
       <div class="titre">
        <h3>
         {{item.artist.nickname}}
        </h3>
        <h1>
         {{item.title}}
        </h1>
       </div>
       <div style="text-align: center;">
           <a href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}"><i class="fa fa-step-backward fa-2x"></i></a> &nbsp; &nbsp; &nbsp;
           <a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }} {% endif %}"><i class="fa fa-step-forward fa-2x"></i></a></div>
       <div class="lecteur">
        <audio class="fc-media" style="width: 100%;">
         <source src="{% if item.audio_file %}{{item.audio_file.url}} {% else %} {{item.audio_link}} {% endif %}" type="audio/mp3"/>
        </audio>

       </div>
       {% endfor %}
      </div>
     </div>
    </div>
{%endblock%}

player/templates/index11.html
{% extends 'base.html'%}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'index.css' %}" rel="stylesheet"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Prompt:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=IM+Fell+English+SC&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital,wght@1,200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Prompt:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <title>{%block title%}OYU-LIVE{%endblock%}</title>
</head>
<body>
{%block body%}
  <div class='info'>
     <h2>What is OYU LIVE?</h2>
     <p>
      OYU - būl jandy dauyspen oryndalatyn jäne är türli janrga jatatyn ärtister änderiniñ jinagy.
      Üshinshi bölim episodtary är beysenbi saiyn shygatyn bolady. </p>
  </div>

  <div class='info' style="margin-top: 0;">
    <h2>OUR ARTISTS</h2>
    <div style="width: 80%;">
    <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="3" aria-label="Slide 4"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="4" aria-label="Slide 5"></button>
      </div>

      <div class="carousel-inner" >
          {% for item in page_obj %}
              {% if item.pk == 1 %}
                <div class="carousel-item active">
                {% else %}
              <div class="carousel-item ">
              {% endif %}
{#              <div class="carousel-item">#}
                  <a href="songs/{{item.nickname}}">
                  <img src="{{item.image.url}}" style="width: 1000px;height:500px;object-fit:cover;" alt="..." ></a>
                    <h3>
                        {{item.nickname}}
                    </h3>
              </div>
       {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
  </div>
</div>
    <script src="{% static 'JS' %}/bootstrap.min.js"></script>
    <script src="{% static 'JS' %}/swiper.min.js"></script>
    <script src="{% static 'JS' %}/purecounter.min.js"></script>
    <script src="{% static 'JS' %}/isotope.pkgd.min.js"></script>
    <script src="{% static 'JS' %}/scripts.js"></script>
  </div>
  <div class="info">
    <h2>News</h2>
    <div class="main">

      <div class="song">
        <a href="https://www.youtube.com/watch?v=7DcoGxSZ43k">
        <img src="Images/mdee-goroskop-fm.jpg" alt="" width="auto" height="250" style="border-radius: 10px;"> </a>
        <h6>Гороскоп FM M'dee</h6>
        <h6>Релиз альбома</h6>
      </div>

      <div class="song">
        <a href="https://www.youtube.com/watch?v=_QuNHAEQwyM">
          <img src="Images/dose.jpg" alt="" width="auto" height="250" style="border-radius: 10px;"> </a>
          <h6>Праздник</h6>
          <h6>M'Dee & Darrem</h6>
      </div>

      <div class="song">
        <a href="https://youtu.be/RLOkg0V1TSk">
          <img src="Images/zoloto.jpg" alt="" width="auto" height="250" style="border-radius: 10px;"></a>
          <h6>Закрытый клуб</h6>
          <h6>M'Dee & ANIKV</h6>
      </div>

      <div class="song">
        <a href="https://youtu.be/3hBrqQEc7tw">
          <img src="Images/qazaq-lofi.jpg" alt="" width="auto" height="250" style="border-radius: 10px;"></a>
          <h6>Qazaq-Lofi</h6>
          <h6>OYU EDITION</h6>
      </div>
      <div class="song">
        <a href="https://www.youtube.com/watch?v=Vf3sDdFSv1k">
        <img src="Images/hiroo.jpg" alt="" width="auto" height="250" style="border-radius: 10px;"></a>
        <h6>Tutin / Особо крутая</h6>
        <h6>Hiro</h6>
      </div>
      <div class="song">
          <img src="Images/Закрытый.jpg" alt="" width="auto" height="250" style="border-radius: 10px;">
          <h6>Закрытый клуб</h6>
          <h6>M'Dee & ANIKV</h6>
      </div>
      <div class="song">
          <img src="Images/Party.jpg" alt="" width="auto" height="250" style="border-radius: 10px;">
          <h6>Праздник</h6>
          <h6>M'Dee & Darrem</h6>
      </div>
      <div class="song">
          <img src="Images/Унисон.jpg" alt="" width="auto" height="250" style="border-radius: 10px;">
          <h6>Унисон</h6>
          <h6>M'Dee</h6>
      </div>
    </div>
  </div>

</body>
{%endblock%}
</html>

player/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    {% load static %}
    <link href="{% static 'login.css' %}" rel="stylesheet"/>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	<title>Login</title>
	<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
</head>
<body>
<div class="login-box">
	<h1>Login</h1>
    <form method="POST", action="">
        {% csrf_token %}

	<div class="form">
		<ul id="form-messages">
		</ul>
	</div>
	<div class="textbox">
		<i class="fas fa-user"></i>
		<input type="text" id="username" placeholder="Username" name="username" value="">
	</div>

	<div class="textbox">
		<i class="fas fa-lock"></i>
		<input type="password" id="password" placeholder="Password" name="password" value="">
	</div>
    <input class="btn" type="submit" name="Log in" value="Sign In">
{#	<button class="btn" id="btn-submit" onclick="login()" name="" >Sign In#}
{#	</button>#}
    </form>
    {% for message in messages %}

        <p>{{ message }}</p>

    {% endfor %}

	<div class="signup">
		Don't have account?  <a href="{% url 'player:signup' %}"> Sign Up</a>
	</div>
</div>

<script>
	function login(){
		var xhttp = new XMLHttpRequest();
	  	xhttp.onreadystatechange = function() {
	    	if (this.readyState == 4 && this.status == 200) {
	  	    	document.getElementById("form-messages").innerHTML =
	        	this.responseText;
	     	}
	    };
	    xhttp.open("POST", "ajax-info.txt", true);
	    xhttp.send();
	};



</script>




</body>
</html>

player/templates/playlists.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>create</title>
</head>
<body>
    <h2>{{playlist.title}}</h2>
    {% for items in playlist.songs.all %}
    <h2>{{items.title}}</h2>
    {% endfor %}
</body>
</html>

player/templates/signup.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Sign Up</title>
    {% load static %}
    <link href="{% static 'signup.css' %}" rel="stylesheet"/>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<body onload="setdate()">

<form method="POST" action="">
    {% csrf_token %}
    <div class="sign__box">
	<h1>Create your Account</h1>
	<div class="container">
		<div class="personal">
			<h3>Personal Information</h3>
			<div class="textbox">
				<i class="fas fa-user"></i>
                {{ form.first_name }}
{#				<input type="text" placeholder="First name">#}
			</div>


			<div class="textbox">
				<i class="fas fa-user"></i>
				{{ form.last_name }}
			</div>

			<div class="textbox">
				<i class="fas fa-envelope"></i>
				{{ form.email }}
			</div>

			<div class="choose">
				<select class="select">
					<option value="0">City</option>
					<option value="1">Astana</option>
					<option value="2">Almaty</option>
					<option value="3">Shymkent</option>
					<option value="4">Turkestan</option>
					<option value="5">Taraz</option>
					<option value="6">Semey</option>
					<option value="7">Aqtobe</option>
					<option value="8">Zhezqazgan</option>
					<option value="9">Oral</option>
				</select><br>
				<input type="date" name="Birhday" value="Birhday"><br>
			</div>

			<div class="gender">
				<label class="gen">Male
					<input type="radio" name="gender">
				<label class="gen">Female
					<input type="radio" name="gender">
			</div>
		</div>

		<div class="account">
			<h3> Account Information</h3>
			<div class="textbox">
				<i class="fas fa-user"></i>
				{{ form.username }}
			</div>

			<div class="textbox">
				<i class="fas fa-key"></i>
				{{ form.password1 }}
			</div>

			<div class="textbox">
				<i class="fas fa-key"></i>
				{{ form.password2 }}
			</div>

			<div class="check">
				<input type="checkbox">
				<label>Accept the terms and policies</label>
			</div>
			<input class="btn" type="submit" name="Create User" value="Sign In">
		</div>
	</div>
        {{ form.errors}}

        <a href="{% url 'player:login' %}">log in</a>
</div>
</form>



<!-- <script type="text/javascript">
	function setdate(){
        var today = new Date();
    	var dd = today.getDate();
    	var mm = today.getMonth()+1; //January is 0!
    	var yyyy = today.getFullYear();
     	if(dd<10){
           	dd='0'+dd
        } 
        if(mm<10){
           	mm='0'+mm
        } 
   		today = yyyy+'-'+mm+'-'+dd;
   		document.getElementById("1").setAttribute("max", today);
	}
</script> -->

</body>
</html>